name: Generate snake animation

on:
  workflow_dispatch: # Manually triggered

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use Node.js 16

      - name: Install dependencies
        run: npm install

      - name: Generate snake.svg
        run: npx -p snake-github-cli snake

      - name: Move snake.svg to README files folder
        run: mv snake.svg "README files/"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update snake.svg"
          git push
